### ISSUE TITLE
abnormal beat annotations

### ISSUE THREAD

**Issue by SunnyCYC** [fosfrancesco/asap-dataset#3] opened 2021-07-16 09:01 UTC
Dear Authors, 

Thanks for the great work!
However, I found some errors in beat annotations while calculating statistics regarding inter-beat-intervals(IBI) for all beats.
I converted all IBI into BPM, and found 19 songs with max tempo larger than 300 bpm.
You may check the .xlsx (https://drive.google.com/file/d/1mluXcJQQGjr-K5Cm0JAoFBP521eSUKgK/view?usp=sharing) for these songs. Especially for the song Beethoven/Piano_Sonatas/26-3/HONG05M.wav, the fastest beat is 6000bpm.
(a screenshot for the corresponding annotations is also shown in the .xlsx)

Could you please check if there's any systematic error in the automatic annotation algorithm that cause this?
If there's any further information required from me, please let me know.
Thank you!

**Comment by fosfrancesco** [comment] 2021-07-16 09:50
Thank you for reporting this!
A systematic error is very unlikely. But there could be several reasons for those annotations:
- rubato
- player mistake (e.g. if a player skip a note that is beat long, there will be two beats that are very close)
- an error in the note2note alignment algorithm output

If the cause is the last one, I will manually correct the annotations. Unfortunately I will be able to do so only next month.

Francesco

**Comment by SunnyCYC** [comment] 2021-07-16 13:39
Good to hear that it's very unlikely systematic.
Thanks for your quick response and help!

**Comment by apmcleod** [comment] 2021-08-03 11:29
Hello @SunnyCYC, thank you for the bug report, and apologies for the delay. I have checked into all of the pieces in the file you linked.

The Beethoven example is an issue where the performer did not take a repeat but the score repeats. Therefore, the alignment has placed one entire repeat within a rest in the score (so "missed" notes don't overlap with any existing notes), and then resumed as normal. We did notice similar errors with missed repeats in a few other places that we fixed manually (you can see some directories labeled "no repeats"), but apparently we missed this one. I don't think that this is a systematic error since we checked for this, and you found only this one.

All of the other pieces seem to be correct to me, they are just performed with large tempo variations. You can notice that some of the slowest parts tend to be towards the ends of sections, and the faster parts tend to occur during cadenza-type sections where only the right hand is playing a long run.

@fosfrancesco I am re-opening this issue to remind us to manually correct the Beethoven example you linked (Beethoven/Piano_Sonatas/26-3/HONG05M.wav) for our next ASAP release.

**Comment by SunnyCYC** [comment] 2021-08-03 15:35
@apmcleod, 

Thank you very much for the detailed explanation!
And yes, all of the other pieces sounds correct to me, too.
Thanks!

**Comment by fosfrancesco** [comment] 2021-09-14 13:23
The corrected file (Beethoven/Piano_Sonatas/26-3/HONG05M.wav) is now in branch "corrections2", and the asap_annotations.json has been modified accordingly. Thank you again for the report!
We will merge it into main for the next release.

**Closed as completed by fosfrancesco** 2021-09-14 13:23 UTC
